### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by tatsumasagc** [BrianDMG/conv2mp4-py#2]
OS: Windows 10 [version 10.0.19043.1503]
Python: 3.9-64

The filename, directory name, or volume label syntax is incorrect.
Traceback (most recent call last):
  File "D:\conv2mp4\conv2mp4-py.py", line 414, in <module>
    codec_discovery()
  File "D:\conv2mp4\conv2mp4-py.py", line 152, in codec_discovery
    get_vid_codec = subprocess.Popen(ffprobe + " -v error -select_streams v:0 -show_entries stream=codec_name -of "
TypeError: a bytes-like object is required, not 'str'
Exception ignored in: <__main__.Tee object at 0x00000218062C22E0>
AttributeError: 'Tee' object has no attribute 'flush'

**Comment by happyman** [comment]
1. 2to3
2. add "shell=True, encoding='utf-8' in Popen
3. skip plex refresh if plex_ip == ''
runs under Ubuntu Linux 22.04 

https://gist.github.com/happyman/610407127195cfc60fcf902cca7c2d80
